import type { Metadata } from "next";
import { Geist, Geist_Mono, Modak } from "next/font/google";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
          items={[
            { href: "/", label: "Accueil" },
            { href: "/gallery", label: "Galerie" },
            { href: "/services", label: "Services" },
            { href: "/appointment", label: "Rendez-vous" },
          ]}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
